### PR TITLE
relaton/support#33 add cimas

### PR DESCRIPTION
**Pull request by CAMOBAP**

### CODE REVIEW

**Comment by CAMOBAP** [comment]
cc @opoudjis @andrew2net

**Comment by andrew2net** [comment]
@CAMOBAP, this repo was created by @opoudjis, I don't know anything about it.

**Comment by CAMOBAP** [comment]
@andrew2net This PR just about adding workflows because I don't have direct write access

**Comment by ronaldtse** [comment]
@CAMOBAP you now have access. Thanks.

**Review by ronaldtse — APPROVED** [review]

**Comment by opoudjis** [comment]
Yes. I need it as a grammar component to constrain the metadata of the new Plateau gem. In time @andrew2net may or may not need to use it, if the Japanese Ministry of Land &c ever use us to publish their bibliographic records.

**Pull request merged**
